name: CI

on:
  push:
    branches:
      - master
  release:

  create:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: |
        ${{ startswith(github.ref, 'refs/tags/') }} && TAG_NAME=$(basename ${{ github.ref }})
        echo $TAG_NAME
