name: CI

on:
  create:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: |
        echo $GITHUB_REF
        echo $GITHUB_SHA
        echo ${{ github.ref }}
        echo ${{ github.sha }}
