name: CI

on:
  push:
    branches: 
      - master
      - feature/**
    paths:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
